[package]
name = "rusty-apple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
ffmpeg-next="7.1.0"
flager = "0.0.9"
image="0.25.5"
prometheus="0.13.4"
teloxide = "0.13.0"
